### ISSUE TITLE
Connection polling failed: [Errno 9] Ungültiger Dateideskriptor

### ISSUE THREAD

**Issue by wil76** [knxd/knxd#284]
any idea where this is coming from ?

```
2017-08-20  23:27:51 ERROR    Main         Connection polling failed: [Errno 9] Ungültiger Dateideskriptor
Traceback (most recent call last):
  File "smarthome.py", line 416, in start
    self.connections.poll()
  File "/usr/local/smarthome/lib/connection.py", line 100, in poll
    self._epoll.modify(fileno, self._ro)
OSError: [Errno 9] Ungültiger Dateideskriptor
2017-08-20  23:27:51 ERROR    Main         Connection polling failed: [Errno 9] Ungültiger Dateideskriptor
Traceback (most recent call last):
  File "smarthome.py", line 416, in start
    self.connections.poll()
  File "/usr/local/smarthome/lib/connection.py", line 100, in poll
    self._epoll.modify(fileno, self._ro)
OSError: [Errno 9] Ungültiger Dateideskriptor
2017-08-20  23:27:51 ERROR    Main         Connection polling failed: [Errno 9] Ungültiger Dateideskriptor
Traceback (most recent call last):
  File "smarthome.py", line 416, in start
    self.connections.poll()
  File "/usr/local/smarthome/lib/connection.py", line 100, in poll
    self._epoll.modify(fileno, self._ro)
OSError: [Errno 9] Ungültiger Dateideskriptor
```
obviously this has been looping for a longer time, but disappeared after some time with tons of log entries.
-----   Init SmartHomeNG 1.3x.ee85750.dev   -----

**Comment by mike-kfed** [comment]
Normally you get Errno 9 when a file-handle was closed "from outside" while it was still opened in a running python script, when python then closes the file (through the GC or calling `f.close()`) it can't and complains. Don't know hat smarthome.py does, but if it uses a unix socket to talk to knxd it may contain a race condition and weird closing of file handle code?

**Comment by smurfix** [comment]
This is not a knxd problem.
