### ISSUE TITLE
router: setup router: failed

### ISSUE THREAD

**Issue by songzh96** [knxd/knxd#487]
HI

My knxd often crashes, after checking the log
I found this
```
Sep 16 10:11:52 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Sep 16 10:11:52 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 289.
Sep 16 10:11:52 raspberrypi systemd[1]: Stopped KNX Daemon.
Sep 16 10:11:52 raspberrypi systemd[1]: Starting KNX Daemon...
Sep 16 10:11:52 raspberrypi knxd[4389]: KOMEN: E00000064: [28:router] router: setup router: failed
Sep 16 10:11:52 raspberrypi knxd[4389]: KOMEN: F00000105: [16:server] Link down, terminating
Sep 16 10:11:52 raspberrypi systemd[1]: Started KNX Daemon.
Sep 16 10:11:52 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 10:11:52 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'
```

this is my config file
`KNXD_OPTS="-e 1.1.111 -E 1.1.112:8 -u /tmp/eib -n KOMEN  -DTRS -b tpuarts:/dev/ttyAMA0"`

 Anyone Can help me;

Thank you

**Comment by shacal** [comment]
Same behaviour happening here in Debian and Ubuntu wwith knxd 0.14.39

**Comment by migabc** [comment]
Hi,

I've been experiencing the same issue since I've upgraded from jessie to stretch and then buster.
the buster upgrade also upgraded my knxd (now v0.14.30) and this new version of knxd is often crashing with these errors:

`
Nov  5 15:20:59 raspberrypi knxd[1410]: **E00000046: [ 4:server] Communication error: Network is unreachable**
Nov  5 15:20:59 raspberrypi knxd[1410]: **F00000105: [ 4:server] Link down, terminating**
Nov  5 15:20:59 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Nov  5 15:20:59 raspberrypi homebridge[1420]: [11/5/2020, 3:20:59 PM] [homebridge-knx.KNX] FATAL: knxd or eibd not reachable
Nov  5 15:20:59 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov  5 15:20:59 raspberrypi homebridge[1420]: [11/5/2020, 3:20:59 PM] Error: Cannot reach knxd or eibd service, please check installation and knx_config.json
Nov  5 15:20:59 raspberrypi homebridge[1420]:     at Socket.<anonymous> (/usr/lib/node_modules/homebridge-knx/lib/knxmonitor.js:23:10)
Nov  5 15:20:59 raspberrypi homebridge[1420]:     at Socket.emit (events.js:198:15)
Nov  5 15:20:59 raspberrypi homebridge[1420]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Nov  5 15:20:59 raspberrypi homebridge[1420]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Nov  5 15:20:59 raspberrypi homebridge[1420]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
Nov  5 15:20:59 raspberrypi homebridge[1420]: [11/5/2020, 3:20:59 PM] Got SIGTERM, shutting down Homebridge...
Nov  5 15:21:04 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Nov  5 15:21:04 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Nov  5 15:21:09 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Nov  5 15:21:09 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 13.
Nov  5 15:21:09 raspberrypi systemd[1]: Stopped KNX Daemon.
Nov  5 15:21:09 raspberrypi systemd[1]: Starting KNX Daemon...
Nov  5 15:21:09 raspberrypi knxd[1900]: **E00000064: [16:router] router: setup router: failed**
Nov  5 15:21:09 raspberrypi knxd[1900]: **F00000105: [ 4:server] Link down, terminating**
Nov  5 15:21:09 raspberrypi systemd[1]: Started KNX Daemon.
Nov  5 15:21:09 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Nov  5 15:21:09 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov  5 15:21:14 raspberrypi systemd[1]: homebridge.service: Service RestartSec=10s expired, scheduling restart.
Nov  5 15:21:14 raspberrypi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 6.
Nov  5 15:21:14 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Nov  5 15:21:14 raspberrypi systemd[1]: Started Node.js HomeKit Server.
`

Any help appreciated

**Comment by smurfix** [comment]
Do you have a default route?

**Comment by migabc** [comment]
Yes, it's my router

pi@raspberrypi:~ $ netstat -nrt
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 wlan0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 wlan0
pi@raspberrypi:~ $

**Comment by migabc** [comment]
It runs OK most of the times but then suddenly is starts crashing 

i@raspberrypi:~ $ systemctl status knxd
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-11-05 18:52:54 WET; 2min 12s ago
 Main PID: 10748 (knxd)
    Tasks: 1 (limit: 2063)
   CGroup: /system.slice/knxd.service
           └─10748 /usr/bin/knxd -e 0.0.100 -E 0.0.101:7 -D -T -R -S -i 6720 -b tpuarts:/dev/ttyKNX1

Nov 05 18:52:54 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 18:52:54 raspberrypi systemd[1]: Started KNX Daemon.
Nov 05 18:52:54 raspberrypi knxd[10748]: F00000106: [16:router] internal error: send_more is not set
pi@raspberrypi:~ $ 


It was running fine when I was on jessies (manually installed knxd 0.12.15-2) but now on buster (automatically installed knxd 0.14.30) it seems very unstable

**Comment by smurfix** [comment]
Please test whether the problem still exists in the current version ("debian" branch).

**Comment by migabc** [comment]
Can you please explain how to install that version?

**Comment by smurfix** [comment]
https://github.com/knxd/knxd/tree/debian#building

**Comment by migabc** [comment]
Thanks for your help :-)
Now running:
pi@raspberrypi:~ $ knxd -V
knxd DEBIAN-0.14.39-1-7-g54ef8bb

Now I'm getting these errors:

Nov  5 19:39:40 raspberrypi systemd[1]: Starting KNX Daemon...
Nov  5 19:39:40 raspberrypi knxd[1359]: E00000013: [19:A.tcp] OpenInetSocket 6720: bind: Address already in use
Nov  5 19:39:40 raspberrypi knxd[1359]: F00000105: [19:A.tcp] Link down, terminating

**Comment by smurfix** [comment]
So kill off the old knxd, and/or the systemd socket that's still listening.
`systemctl stop knxd.socket`

**Comment by migabc** [comment]
Is that the new way of running knxd (via systemd socket)?

Anyway:
Comment-out the knxd.socket entries in /lib/systemd/system/knxd.service:

pi@raspberrypi:~ $ grep -i socket /lib/systemd/system/knxd.service
After=network.target #knxd.socket
#Requires=knxd.socket
#Also=knxd.socket
pi@raspberrypi:~ $ 

and restarted the service 
pi@raspberrypi:~ $ sudo systemctl stop knxd.service
pi@raspberrypi:~ $ sudo systemctl daemon-reload
pi@raspberrypi:~ $ sudo systemctl start knxd.service

Seems to be running OK now:

pi@raspberrypi:~ $ sudo systemctl status knxd.service
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-11-05 19:50:47 WET; 8s ago
 Main PID: 2210 (knxd)
    Tasks: 1 (limit: 2063)
   CGroup: /system.slice/knxd.service
           └─2210 /usr/bin/knxd -e 0.0.100 -E 0.0.101:100 -D -T -R -S -i 6720 -b tpuarts:/dev/ttyKNX1

Nov 05 19:50:47 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 19:50:47 raspberrypi systemd[1]: Started KNX Daemon.
pi@raspberrypi:~ $

**Comment by migabc** [comment]
Ooops, 
Spoke too soon
It just crashed again :-(

Nov  5 20:03:56 raspberrypi knxd[2749]: E00000064: [20:router] router: setup router: failed
Nov  5 20:03:56 raspberrypi knxd[2749]: F00000105: [ 4:server] Link down, terminating
Nov  5 20:03:56 raspberrypi systemd[1]: Started KNX Daemon.
Nov  5 20:03:56 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Nov  5 20:03:56 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov  5 20:04:07 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Nov  5 20:04:07 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 4.
Nov  5 20:04:07 raspberrypi systemd[1]: Stopped KNX Daemon.
Nov  5 20:04:07 raspberrypi systemd[1]: Starting KNX Daemon...
Nov  5 20:04:07 raspberrypi knxd[2755]: E00000064: [20:router] router: setup router: failed

**Comment by smurfix** [comment]
No idea what's happening here. Please turn on logging (-t1022 -f9, first arguments).

**Comment by migabc** [comment]
It seems that knxd does not run stable under buster
Rolled back to stretch.
Problem solved - now knxd runs perfectly fine

**Comment by tunm1228** [comment]
Why i run: systemctl stop knxd.socket then "Failed to stop knxd.socket: Unit knxd.socket not loaded."?. Please help me?

**Comment by dallmair** [comment]
Unfortunately, this issue is not actionable as it does not contain the necessary information to help and it's impossible to diagnose without the requested debug log.

If you still encounter this issue with the current version of knxd, please collect a debug log and post it here.

In the meantime, I assume the problem has either been fixed already or it might be the somewhat hidden `internal error: send_more is not set`, which has also been reported in #267 and #297. In both cases it does not make sense to keep this issue open, thus I'm closing it now. If it turns out to still affect the current version and have a different root cause than the issues I referred to in this paragraph, we can always reopen it.
